### ISSUE TITLE
Rollout

### ISSUE THREAD

**Issue by judepereira** [asyncy/alpha#3]
## Alpha is defined as:
1. Ability to invoke services seamlessly via any container with a microservice.yml file
2. Outputs of services are can be manipulated - used as inputs to other services
3. Simple constructs such as if, foreach, work with outputs of services
4. People can register their own repos with a microservice.yml in the graphql

## Todos:
- [ ] Resolve all issues under the alpha milestone
- [ ] Modify asyncy deploy to attempt to compile the stories before doing a git push
- [ ] Lock down the version of storyscript in the cli, the bootstrap and the engine to a well known working one which addresses all the issues marked as alpha
- [ ] Test this rigorously in house
- [ ] Make it available to early testers
- [ ] For all built in services, ensure that their representation in the hub is correct - known issue - some show up with a command called 'entrypoint" .

Once this is done, we should have a stable platform, and the immediate follow up on this is
1. Documentation
2. At least 5 use cases, starting with a simple hello world, to a full blown redis, queue, etc example
